// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Expense struct {
	ID       string
	UserID   string
	Amount   float64
	Category string
}

type User struct {
	ID             string
	Name           string
	IsActive       bool
	ExpirationDate time.Time
}
